### ISSUE TITLE
Use container instead Yii

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/log#11]
Starting from this issue https://github.com/yiisoft/yii-swiftmailer/issues/7,
I think that the first step to avoid requiring app component inside external components (logger, mailer, etc..) is to remove Yii references and insert di\Container reference, that it is more general.

In this line:

https://github.com/yiisoft/log/blob/30d24a57ebce472930de4e2cedc5e84b324ee4ed/src/Logger.php#L117

I'd replace with something \yii\di\Container::get()->createObject($target), so we start removing Yii direct references from code. Now we have not a static method to get the container instance, but we have only it in \yii\helpers\BaseYii.

Finally, to allow serialization, we should avoid to inject class and object references inside a variable, such as `$target`. If we put in `$target` only class reference, the serialization will be always possible. Otherwise, the result is not predictable.

So we should have `$target` and `$targetInstances` inside Logger class, where `$targetInstances` are instances of definitions or classes defined in `$target`.

**Comment by hiqsol** [comment]
> I'd replace with something \yii\di\Container::get()->createObject($target), so we start removing Yii direct references from code

It is better then it is now, but unfortunately, it's not a final fix.
A DI container should not be used explicitly, it breaks the DI/IoC idea.

The proper solution should not use DI explicitly or hide it behind some TargetFactory...
Maybe Logger could not create targets but receive them at constructor...
I don't have an ideal solution right now that's why I just left it as is.

@samdark, @SilverFire do you have ideas?

**Comment by FabrizioCaldarelli** [comment]
> Maybe Logger could not create targets but receive them at constructor...

I thought it, but there is also `addTarget` method to add targets dinamically.

**Comment by samdark** [comment]
1. This package has no reason to be container-aware.
2. This package has no reason to use Yii-specific dependencies.

> Maybe Logger could not create targets but receive them at constructor...

Yes. That's what should be done.

> I thought it, but there is also `addTarget` method to add targets dynamically.

That sounds fine. What's the problem with it?

**Comment by FabrizioCaldarelli** [comment]
> > I thought it, but there is also `addTarget` method to add targets dynamically.
> 
> That sounds fine. What's the problem with it?

Because `addTarget` could accept class definition or objects. So it is required \yii\di\Container or Yii to load them.

**Comment by samdark** [comment]
Let's remove accepting definitions.

**Comment by FabrizioCaldarelli** [comment]
> Let's remove accepting definitions.

But creating Logger from config will use definitions, so DI will be required inside Logger constructor.

**Comment by samdark** [comment]
It should not be. Logger should accept an array of targets and that's it.

**Comment by machour** [comment]
Fixed by #16
