### ISSUE TITLE
Implement psr-3@1.1.0 tests?

### ISSUE THREAD

**Issue by machour** [yiisoft/log#15]
psr-3 had a new version introducing a phpunit test to check the implementation. 

Might be useful to implement it: https://github.com/php-fig/log/releases/tag/1.1.0

**Comment by machour** [comment]
Likely to be moved in a separate package 
https://groups.google.com/forum/?fromgroups#!topic/php-fig/DsmK600GAas

**Comment by samdark** [comment]
Then this is something we don't want right now.
