### ISSUE TITLE
Removing the yiisoft/yii-core dependency

### ISSUE THREAD

**Issue by machour** [yiisoft/log#17]
Here are the current issues with the log packages, preventing them from being used outside of Yii:

## yiisoft/log

The package currently depends on yii-core for the following reasons:

#### \Yii\Log\LogRuntimeException

- [x] Extends `yii\exceptions\Exception`

#### \Yii\Log\Logger

- [x] Uses `yii\base\ErrorHandler::convertExceptionToString()` to format dispatch failure exception.
- [x] Uses `YII_BEGIN_TIME` constant (it is defined in `yii-core/config/defines.php`)
- [x] Uses `yii\helpers\VarDumper` but checks for availability.

#### \Yii\Log\LoggerTarget

- [x] Uses `yii\exceptions\InvalidConfigException`

#### \Yii\Log\Target

- [x] Extends `yii\base\Component`
- [x] Uses `YII_BEGIN_TIME`
- [x] Uses `yii\helpers\VarDumper`
- [x] Uses `yii\helpers\ArrayHelper`
- [x] Uses `yii\helpers\StringHelper`

## yiisoft/log-target-db

- [x] Uses `yii\exceptions\InvalidConfigException`
- [x] Uses `yii\helpers\VarDumper`

## yiisoft/log-target-email

- [ ] Uses `yii\mail\MailerInterface`
- [ ] Uses `yii\mail\MessageInterface`
- [ ] Uses `yii\di\AbstractContainer` to configure the Message
- [ ] Uses `yii\exceptions\InvalidConfigException`

## yiisoft/log-target-file

- [x] Uses `yii\helpers\FileHelper` to create a directory
- [x] Uses `yii\exceptions\InvalidConfigException`
- [x] Uses `yii\helpers\Yii` to resolve aliases

## yiisoft/log-target-syslog

Nothing :tada:

**Comment by machour** [comment]
Proposals:

**exceptions:** 

Libraries should define their own base exception class, extending from \Exception.

Libraries should define all the exceptions they thrown (unless it's from a required package).

(i.e. `\Yii\Log\Exceptions\InvalidConfigException` extends `\Yii\Log\Exceptions\Exception` extends `\Exception`)

Furthermore, I'd like to rename `\Yii\Log\LogRuntimeException` to `\Yii\Log\Exceptions\RuntimeException` (and adopt this folder for other packages)

**helpers:**

We need to extracts our helpers into `yiisoft/helpers`.

**YII\_BEGIN\_TIME:**

The application start time should be provided in `Logger::__construct()`

Questions

**yii vs non-yii:**

Should `log-target-file` try to resolve aliases when it detects Yii, and skip that otherwise?

**Comment by samdark** [comment]
> Libraries should define their own base exception class, extending from \Exception.

It is better to extend exception from \RuntimeException, not from \Exception in this case.

> We need to extracts our helpers into yiisoft/helpers.

I think that having all helpers in a single package isn't good. Having multiple packages would make more sense.

> Should log-target-file try to resolve aliases when it detects Yii, and skip that otherwise?

No.

**Comment by samdark** [comment]
Created two repos:

- https://github.com/yiisoft/string
- https://github.com/yiisoft/array
