### ISSUE TITLE
Wish: Add LogTarget that prints to standard output, and make it default in console config

### ISSUE THREAD

**Issue by fsateler** [yiisoft/log#20]
I have been bitten quite a few times when (for example) cache/flush-all doesn't work because of permissions issue (say, the cache files are owned by www-data), and in turn the error messages are redirected to the app log... which can't be written because it is owned by www-data too.

The console commands should default to printing everything on stderr, and that should include warning/error log messages.

**Comment by machour** [comment]
Shouldn't this Logger be in yii-console instead?

**Comment by samdark** [comment]
Could be, yes.
