### ISSUE TITLE
Log Formatting

### ISSUE THREAD

**Issue by KnightYoshi** [yiisoft/log#22]
Log formatting should be able to be changed easily by setting a property in the config file.
Additionally it should accept Mapped Diagnostic Constant like what Log4PHP and Log4J have. So that other data can be added to the left of the message.

Using Log4PHP this is the pattern we use
`'[%-5.5p] [%d{H:i:s}] [%X{username}] [%-15.15logger] [%-3.3line] | %message - %relative(ms)%newline'`

Which is the log type (info, debug, error, fatal, warn), timestamp, MDC username, the logger name (always 15 characters), the line it was called on, and the message.

Also as a side note if a debug log type could be added that would be appreciated as well.

**Comment by devanych** [comment]
https://github.com/yiisoft/log/commit/c41b44872b9b577219728863c99a2c2ac787ea1d
