### ISSUE TITLE
Info log messages ignore level filtering

### ISSUE THREAD

**Issue by Kolyunya** [yiisoft/log#3]
### What steps will reproduce the problem?
Implement a custom log target. Configure it to receive only `error` messages. Produce a single `error` message. Inspect `$this->messages` from the `export()` method of the custom log target.

### What is the expected result?
A single `error` message.

### What do you get instead?
Two messages. An expected `error` message and another `info` message with the request context.

### Additional info
This is caused by [this code block](https://github.com/yiisoft/yii2/blob/master/framework/log/Target.php#L127-L129). An `info` message is being appended to other messages _after_ filtering has already been performed.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1
| Operating system | GNU/Linux

**Comment by alireza-salehi** [comment]
i have same issue, 
`		'log'                => [
			'targets' => [
				[
					'class'    => 'yii\log\DbTarget',
					'logTable' => 'yiilog',
					'db'       => 'applog',
					'levels'   => [ 'error', 'warning' ]
				],
			],
		]
`
with every error log , there i an info log with full context output,
impact on performance. and log DB size.

**Comment by alexkart** [comment]
@alireza-salehi, as @rob006 said you can set `logVars` to an empty array and context won't be logged.
See https://www.yiiframework.com/doc/guide/2.0/en/runtime-logging

```php
[
    'class' => 'yii\log\FileTarget',
    'logVars' => [],
]
```
