### ISSUE TITLE
Add analog of monolog processors

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/log#59]
In the monolog you can attach a set of [processors](https://github.com/Seldaek/monolog/blob/main/doc/02-handlers-formatters-processors.md#processors) to each log target. It would be good to give ability to users to add global and per-target processors.

**Comment by samdark** [comment]
We already have CommonContext capable of doing almost the same. Along with the message formatting, it covers the functionality so there's no need for separate processors.
