### ISSUE TITLE
Log change level to int

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/log#7]
What is the purpose of this file?

Level is a character, so tests will fail with this migration

https://github.com/yiisoft/log/blob/00554d78caaaa56c87a002a71191d647f4e29ba0/src/migrations/m180103_040100_log_change_level_to_int.php#L16

**Comment by machour** [comment]
See #6

**Comment by FabrizioCaldarelli** [comment]
I think that it ca ben safely deleted that migration, because it is in tests folder. So I don't think that it will be called when log package is installed.

**Comment by rob006** [comment]
> because it is in tests folder

What do you mean by that? Migrations are in `src` directory.

**Comment by FabrizioCaldarelli** [comment]
I'm sorry, I saw it wrong.

Do we want to create another migration to delete that changes or remove it ?

**Comment by rob006** [comment]
https://github.com/yiisoft/yii2/commit/481970957b18fd3b7c1a031984d3826249208563 and https://github.com/yiisoft/log/commit/00554d78caaaa56c87a002a71191d647f4e29ba0 should be reverted and new migration should be created that changes type from int to string (see #6).

**Comment by FabrizioCaldarelli** [comment]
I've decided to leave so https://github.com/yiisoft/log/pull/8/files/52bb835aec15de83db5242201c4d3df1ec08911d#diff-24b65337bd78063bc186ddce3a5fb938
