### ISSUE TITLE
The `Formatter::getTime()` function depends on the global locale

### ISSUE THREAD

**Issue by ezoterik** [yiisoft/log#76]
### What steps will reproduce the problem?

Set global locale in ru language. For example:

```php
\setlocale(LC_ALL, 'ru_RU')
```

And log any data

### What is the expected result?

The presence of a file with logs in the directory

### What do you get instead?

The file is not created and the logs are not saved

### Additional info

The `Formatter::getTime()` function depends on the global locale. The whole problem is only in this line (which thinks the delimiter will always be a dot) https://github.com/yiisoft/log/blob/a1256a964f2a504c455ee04767fb9eebf60052d0/src/Message/Formatter.php#L144

If the decimal separator is a comma (due to the locale), then we get an error:
> Unable to send log via Yiisoft\Log\Target\File\FileTarget: Error: Call to a member function format() on bool

I created a PR with a proposal to solve this problem: https://github.com/yiisoft/log/pull/75

| Q                | A
| ---------------- | ---
| Version          | 1.0.3
| PHP version      | 7.4
| Operating system | Any

**Comment by terabytesoftw** [comment]
https://3v4l.org/VqNeW#v7.4.28
