### ISSUE TITLE
Warning: Array to string conversion in vendor\yiisoft\log\src\Message.php on line 116

### ISSUE THREAD

**Issue by ghost** [yiisoft/log#89]
##Warning: Array to string conversion in vendor\yiisoft\log\src\Message.php on line 116
`$context[$placeholderName]`

Need handler for different types.
I use logger for doctrine.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 2.0.0
| PHP version      |  8.1.9
| Operating system | Linux and Windows

**Comment by vjik** [comment]
@fcnybok can you show dump of `$context`?

**Comment by fcnybok** [comment]
> @fcnybok can you show dump of `$context`?

2023-02-02 09:39:13.813900 [info][application] Connecting with parameters Array

Message context:

params: [
    'driver' => 'pdo_pgsql'
    'dbname' => 'manager'
    'host' => 'localhost'
    'password' => '<redacted>'
    'user' => 'postgres'
]
time: 1675330753.813901
memory: 18410928
category: 'application'

**Comment by vjik** [comment]
1) We can add support nested arrays, for example "{foo.bar}" will be use `$context['foo']['bar']` value.
2) Need correctly process non-string values without throw error / exception / warning.
